export const getLocalTime = (country?: string): Date => {
  const countryTimezoneMap: Record<string, string> = {
    // Asia
    Afghanistan: "Asia/Kabul",
    Armenia: "Asia/Yerevan",
    Azerbaijan: "Asia/Baku",
    Bahrain: "Asia/Bahrain",
    Bangladesh: "Asia/Dhaka",
    Bhutan: "Asia/Thimphu",
    Brunei: "Asia/Brunei",
    Cambodia: "Asia/Phnom_Penh",
    China: "Asia/Shanghai",
    Cyprus: "Asia/Nicosia",
    Georgia: "Asia/Tbilisi",
    "Hong Kong": "Asia/Hong_Kong",
    India: "Asia/Kolkata",
    Indonesia: "Asia/Jakarta",
    Iran: "Asia/Tehran",
    Iraq: "Asia/Baghdad",
    Israel: "Asia/Jerusalem",
    Japan: "Asia/Tokyo",
    Jordan: "Asia/Amman",
    Kazakhstan: "Asia/Almaty",
    Kuwait: "Asia/Kuwait",
    Kyrgyzstan: "Asia/Bishkek",
    Laos: "Asia/Vientiane",
    Lebanon: "Asia/Beirut",
    Macau: "Asia/Macau",
    Malaysia: "Asia/Kuala_Lumpur",
    Maldives: "Indian/Maldives",
    Mongolia: "Asia/Ulaanbaatar",
    Myanmar: "Asia/Rangoon",
    Nepal: "Asia/Kathmandu",
    "North Korea": "Asia/Pyongyang",
    Oman: "Asia/Muscat",
    Pakistan: "Asia/Karachi",
    Palestine: "Asia/Gaza",
    Philippines: "Asia/Manila",
    Qatar: "Asia/Qatar",
    "Saudi Arabia": "Asia/Riyadh",
    Singapore: "Asia/Singapore",
    "South Korea": "Asia/Seoul",
    "Sri Lanka": "Asia/Colombo",
    Syria: "Asia/Damascus",
    Taiwan: "Asia/Taipei",
    Tajikistan: "Asia/Dushanbe",
    Thailand: "Asia/Bangkok",
    "Timor-Leste": "Asia/Dili",
    Turkey: "Europe/Istanbul",
    Turkmenistan: "Asia/Ashgabat",
    UAE: "Asia/Dubai",
    "United Arab Emirates": "Asia/Dubai",
    Uzbekistan: "Asia/Tashkent",
    Vietnam: "Asia/Ho_Chi_Minh",
    Yemen: "Asia/Aden",

    // Europe
    Albania: "Europe/Tirane",
    Andorra: "Europe/Andorra",
    Austria: "Europe/Vienna",
    Belarus: "Europe/Minsk",
    Belgium: "Europe/Brussels",
    "Bosnia and Herzegovina": "Europe/Sarajevo",
    Bulgaria: "Europe/Sofia",
    Croatia: "Europe/Zagreb",
    "Czech Republic": "Europe/Prague",
    Denmark: "Europe/Copenhagen",
    Estonia: "Europe/Tallinn",
    Finland: "Europe/Helsinki",
    France: "Europe/Paris",
    Germany: "Europe/Berlin",
    Gibraltar: "Europe/Gibraltar",
    Greece: "Europe/Athens",
    Hungary: "Europe/Budapest",
    Iceland: "Atlantic/Reykjavik",
    Ireland: "Europe/Dublin",
    Italy: "Europe/Rome",
    Kosovo: "Europe/Belgrade",
    Latvia: "Europe/Riga",
    Liechtenstein: "Europe/Vaduz",
    Lithuania: "Europe/Vilnius",
    Luxembourg: "Europe/Luxembourg",
    Malta: "Europe/Malta",
    Moldova: "Europe/Chisinau",
    Monaco: "Europe/Monaco",
    Montenegro: "Europe/Podgorica",
    Netherlands: "Europe/Amsterdam",
    "North Macedonia": "Europe/Skopje",
    Norway: "Europe/Oslo",
    Poland: "Europe/Warsaw",
    Portugal: "Europe/Lisbon",
    Romania: "Europe/Bucharest",
    Russia: "Europe/Moscow",
    "San Marino": "Europe/San_Marino",
    Serbia: "Europe/Belgrade",
    Slovakia: "Europe/Bratislava",
    Slovenia: "Europe/Ljubljana",
    Spain: "Europe/Madrid",
    Sweden: "Europe/Stockholm",
    Switzerland: "Europe/Zurich",
    Ukraine: "Europe/Kiev",
    "United Kingdom": "Europe/London",
    UK: "Europe/London",
    "Vatican City": "Europe/Vatican",

    // Americas
    "Antigua and Barbuda": "America/Antigua",
    Argentina: "America/Argentina/Buenos_Aires",
    Bahamas: "America/Nassau",
    Barbados: "America/Barbados",
    Belize: "America/Belize",
    Bolivia: "America/La_Paz",
    Brazil: "America/Sao_Paulo",
    Canada: "America/Toronto",
    Chile: "America/Santiago",
    Colombia: "America/Bogota",
    "Costa Rica": "America/Costa_Rica",
    Cuba: "America/Havana",
    Dominica: "America/Dominica",
    "Dominican Republic": "America/Santo_Domingo",
    Ecuador: "America/Guayaquil",
    "El Salvador": "America/El_Salvador",
    Grenada: "America/Grenada",
    Guatemala: "America/Guatemala",
    Guyana: "America/Guyana",
    Haiti: "America/Port-au-Prince",
    Honduras: "America/Tegucigalpa",
    Jamaica: "America/Jamaica",
    Mexico: "America/Mexico_City",
    Nicaragua: "America/Managua",
    Panama: "America/Panama",
    Paraguay: "America/Asuncion",
    Peru: "America/Lima",
    "Puerto Rico": "America/Puerto_Rico",
    "Saint Kitts and Nevis": "America/St_Kitts",
    "Saint Lucia": "America/St_Lucia",
    "Saint Vincent and the Grenadines": "America/St_Vincent",
    Suriname: "America/Paramaribo",
    "Trinidad and Tobago": "America/Port_of_Spain",
    USA: "America/New_York",
    "United States": "America/New_York",
    Uruguay: "America/Montevideo",
    Venezuela: "America/Caracas",

    // Africa
    Algeria: "Africa/Algiers",
    Angola: "Africa/Luanda",
    Benin: "Africa/Porto-Novo",
    Botswana: "Africa/Gaborone",
    "Burkina Faso": "Africa/Ouagadougou",
    Burundi: "Africa/Bujumbura",
    Cameroon: "Africa/Douala",
    "Cape Verde": "Atlantic/Cape_Verde",
    "Central African Republic": "Africa/Bangui",
    Chad: "Africa/Ndjamena",
    Comoros: "Indian/Comoro",
    "Democratic Republic of the Congo": "Africa/Kinshasa",
    Djibouti: "Africa/Djibouti",
    Egypt: "Africa/Cairo",
    "Equatorial Guinea": "Africa/Malabo",
    Eritrea: "Africa/Asmara",
    Eswatini: "Africa/Mbabane",
    Ethiopia: "Africa/Addis_Ababa",
    Gabon: "Africa/Libreville",
    Gambia: "Africa/Banjul",
    Ghana: "Africa/Accra",
    Guinea: "Africa/Conakry",
    "Guinea-Bissau": "Africa/Bissau",
    "Ivory Coast": "Africa/Abidjan",
    Kenya: "Africa/Nairobi",
    Lesotho: "Africa/Maseru",
    Liberia: "Africa/Monrovia",
    Libya: "Africa/Tripoli",
    Madagascar: "Indian/Antananarivo",
    Malawi: "Africa/Blantyre",
    Mali: "Africa/Bamako",
    Mauritania: "Africa/Nouakchott",
    Mauritius: "Indian/Mauritius",
    Morocco: "Africa/Casablanca",
    Mozambique: "Africa/Maputo",
    Namibia: "Africa/Windhoek",
    Niger: "Africa/Niamey",
    Nigeria: "Africa/Lagos",
    Rwanda: "Africa/Kigali",
    "Sao Tome and Principe": "Africa/Sao_Tome",
    Senegal: "Africa/Dakar",
    Seychelles: "Indian/Mahe",
    "Sierra Leone": "Africa/Freetown",
    Somalia: "Africa/Mogadishu",
    "South Africa": "Africa/Johannesburg",
    "South Sudan": "Africa/Juba",
    Sudan: "Africa/Khartoum",
    Tanzania: "Africa/Dar_es_Salaam",
    Togo: "Africa/Lome",
    Tunisia: "Africa/Tunis",
    Uganda: "Africa/Kampala",
    Zambia: "Africa/Lusaka",
    Zimbabwe: "Africa/Harare",

    // Oceania
    Australia: "Australia/Sydney",
    Fiji: "Pacific/Fiji",
    Kiribati: "Pacific/Tarawa",
    "Marshall Islands": "Pacific/Majuro",
    Micronesia: "Pacific/Pohnpei",
    Nauru: "Pacific/Nauru",
    "New Zealand": "Pacific/Auckland",
    Palau: "Pacific/Palau",
    "Papua New Guinea": "Pacific/Port_Moresby",
    Samoa: "Pacific/Apia",
    "Solomon Islands": "Pacific/Guadalcanal",
    Tonga: "Pacific/Tongatapu",
    Tuvalu: "Pacific/Funafuti",
    Vanuatu: "Pacific/Efate",
  };

  const timezone = country ? countryTimezoneMap[country] : null;

  if (!timezone) {
    // fallback to UTC
    return new Date();
  }

  const localTimeString = new Date().toLocaleString("en-US", {
    timeZone: timezone,
  });

  return new Date(localTimeString);
};